import os
import re
import sys
import tempfile
import pandas as pd
import numpy as np
from pathlib import Path

from snakemake.utils import logger, min_version

workflow_folder = os.path.dirname(os.path.abspath(workflow.snakefile))

sys.path.append(os.path.join(workflow_folder, "scripts"))
import utils


# add default config
# comand line adds user config
configfile: os.path.join(workflow_folder, "..", "config", "default_config.yaml")


# add defualt values from python (TODO: replace this)
from naive_atlas.make_config import update_config as atlas_update_config

config = atlas_update_config(config)
from naive_atlas.default_values import *  # LOAD HARDCODED values and EGGNOG_HEADER


# minimum required snakemake version
min_version("6.1")


#container: "docker://continuumio/miniconda3:25.3.1-1"
containerized: "/scratch/timothy/tmp/naive_atlas_v0.1.0.sif"

wildcard_constraints:
    binner="[A-Za-z]+",


include: "rules/sample_table.smk"
include: "rules/sra.smk"
include: "rules/download.smk"  # contains hard coded variables
include: "rules/qc.smk"
include: "rules/assemble.smk"
include: "rules/binning.smk"
include: "rules/genomes.smk"
include: "rules/quantify_genomes.smk"
include: "rules/genome_annotation.smk"
include: "rules/gene_prediction.smk"
include: "rules/gene_annotation.smk"
include: "rules/strains.smk"
include: "rules/screen.smk"  # expects function get_input_fastq defined in qc


CONDAENV = "envs"  # overwrite definition in download.smk


localrules:
    all,
    download,
    qc,
    assembly_one_sample,
    assembly,
    binning,
    genomes,
    quantify_genomes,
    genome_annotation,
    gene_prediction,
    gene_annotation,
    strains,
    screen,
    test,



rule all:
    input:
        "finished_download",
        "finished_QC",
        "finished_assembly",
        "finished_binning",
        "finished_genomes",
        "finished_quantify_genomes",
        "finished_genome_annotation",
        "finished_gene_annotation",


## ---- ##
rule test:
    input:
        #expand("{sample}/sequence_quality_control/read_stats/{step}.zip", sample=SAMPLES, step="1_raw")
        ## 1_raw, 2_deduplicated, 3_quality_filtered, 4_decontaminated, 5_final
        expand("{sample}/sequence_quality_control/{sample}_R1.fastq.gz", sample=["N10hybrid"]),
        #expand("{sample}/sequence_quality_control/{sample}_SE.fastq.gz", sample=["N10single"]),
        expand("{sample}/sequence_quality_control/{sample}_LR.fastq.gz", sample=["N10hybrid"]),
        expand("{sample}/sequence_quality_control/read_stats/{step}.zip", sample=["N10hybrid"], step=["1_raw", "2_deduplicated", "3_quality_filtered", "4_decontaminated", "5_final"]),
        expand("{sample}/sequence_quality_control/read_stats/read_counts.tsv", sample=["N10hybrid"]),
        expand("{sample}/sequence_quality_control/read_stats/QC_read_length_hist_{fraction}.txt", sample=["N10hybrid"], fraction=["PE", "SE", "LR"]),
        expand("{sample}/sequence_quality_control/finished_QC", sample=SAMPLES),
        # 1_normalize_reads 2_error_correction
        #expand("{sample}/assembly/reads/2_error_correction_R1.fastq.gz", sample=["N10", "N10interleaved", "N10hybrid"]),
        #expand("{sample}/assembly/reads/2_error_correction_SE.fastq.gz", sample=["N10single"]),
        #expand("{sample}/assembly/reads/2_error_correction_LR.fastq.gz", sample=["N10hybrid", "N10longread"]),
        #expand("{sample}/assembly/{sample}_raw_assembly.fasta", sample=["N10", "N10interleaved", "N10hybrid", "N10single", "N10longread"]),
        #expand("{sample}/assembly/assembly/{sample}_raw_assembly.fasta", sample=["N10longread"]),
        expand("{sample}/finished_assembly", sample=["N10hybrid"]),
    output:
        touch("finished_test"),


## ---- ##
rule download:
    input:
        os.path.join(os.path.realpath(config["database_dir"]), "finished"),
    output:
        touch("finished_download"),


## ---- ##
rule qc:
    input:
        expand("{sample}/sequence_quality_control/finished_QC", sample=SAMPLES),
        read_counts="stats/read_counts.tsv",
        read_length_stats=(
            ["stats/insert_stats.tsv", "stats/read_length_stats.tsv"]
            if PAIRED_END
            else "stats/read_length_stats.tsv"
        ),
        report="reports/QC_report.html",
    output:
        touch("finished_QC"),


## ---- ##
rule assembly_one_sample:
    input:
        get_assembly,
        "{sample}/assembly/contig_stats/postfilter_coverage_stats.txt",
        "{sample}/assembly/contig_stats/final_contig_stats.txt",
    output:
        touch("{sample}/finished_assembly"),

rule assembly:
    input:
        "finished_QC",
        expand("{sample}/finished_assembly", sample=SAMPLES),
        "reports/assembly_report.html",
    output:
        touch("finished_assembly"),


## ---- ##
rule binning:
    input:
        "finished_assembly",
        expand(rules.binning_prokaryotic_genome_stats.output.stats, sample=SAMPLES),
        expand(rules.binning_eukaryotic_genome_stats.output.stats, sample=SAMPLES),
        expand(rules.binning_viral_genome_stats.output.viral_stats, sample=SAMPLES),
        expand(rules.binning_viral_genome_stats.output.plasmid_stats, sample=SAMPLES),
    output:
        temp(touch("finished_binning")),


## ---- ##
def get_bin_reports(wildcards):
    return(expand("reports/bin_report_{lineage}.html", 
                lineage=get_binned_lineages()
            )
    )

rule genomes:
    input:
        "finished_binning",
        "Binning/raw_bins/all.done",
        "genomes/genomes",
        "genomes/unbinned",
        get_bin_reports,
    output:
        temp(touch("finished_genomes")),


## ---- ##
rule quantify_genomes:
    input:
        "finished_genomes",
        "genomes/coverage/coverage.tsv.gz",
        "genomes/coverage/read_stats.tsv",
    output:
        temp(touch("finished_quantify_genomes")),


## ---- ##
def get_genome_annotations():
    annotation_file_names = {
        "gtdb_tree":                      "genomes/annotations/genomes/tree/finished_gtdb_trees",
        "gtdb_taxonomy":                  "genomes/annotations/genomes/taxonomy/gtdb_taxonomy.tsv",
        "dram":                           expand("genomes/annotations/{dataset}/dram/finished", dataset="genomes"),
        "dram_unbinned":                  expand("genomes/annotations/{dataset}/dram/finished", dataset="unbinned"),
        "metaeuk":                        expand("genomes/annotations/{dataset}/metaeuk/finished", dataset="genomes"),
        "metaeuk_unbinned":               expand("genomes/annotations/{dataset}/metaeuk/finished", dataset="unbinned"),
        "mmseqs2_easy_taxonomy":          expand("genomes/annotations/{dataset}/mmseqs2/easy_taxonomy_finished", dataset="genomes"),
        "mmseqs2_easy_taxonomy_unbinned": expand("genomes/annotations/{dataset}/mmseqs2/easy_taxonomy_finished", dataset="unbinned"),
    }
    annotations_requested = config["genome_annotations"]

    try:
        annotations_files = [
            annotation_file_names[an] for an in annotations_requested
        ]
    except Exception as e:
        raise IOError(
            "Error in annotations requested, check config file 'genome_annotations' "
        ) from e

    return annotations_files

rule genome_annotation:
    input:
        "finished_genomes",
        *get_genome_annotations(),
    output:
        temp(touch("finished_genome_annotation")),


## ---- ##
rule gene_prediction:
    input:
        "finished_genome_annotation",
        "genomes/genes/genomes",
        "genomes/genes/unbinned"
    output:
        temp(touch("finished_gene_prediction")),


## ---- ##
def get_gene_annotations():
    annotation_file_names = {
        "eggNOG":           expand("genomes/annotations/{dataset}/genes/eggNOG.tsv.gz", dataset="genomes"),
        "eggNOG_unbinned":  expand("genomes/annotations/{dataset}/genes/eggNOG.tsv.gz", dataset="unbinned"),
        "dram":             expand("genomes/annotations/{dataset}/genes/dram", dataset="genomes"),
        "dram_unbinned":    expand("genomes/annotations/{dataset}/genes/dram", dataset="unbinned"),
        "mmseqs2":          expand("genomes/annotations/{dataset}/genes/mmseqs2/finished", dataset="genomes"),
        "mmseqs2_unbinned": expand("genomes/annotations/{dataset}/genes/mmseqs2/finished", dataset="unbinned"),
    }
    annotations_requested = config.get("gene_annotations", [])

    try:
        annotations_files = [
            annotation_file_names[key] for key in annotations_requested
        ]
    except Exception as e:
        raise IOError(
            "Error in gene_annotations requested, check config file 'gene_annotations' "
        ) from e

    return annotations_files

rule gene_annotation:
    input:
        "finished_genomes",
        get_gene_annotations(),
    output:
        temp(touch("finished_gene_annotation")),


## ---- ##
rule strains:
    input:
        "finished_genomes",
        "genomes/strains/comparison",
    output:
        temp(touch("finished_strains")),


## ---- ##
rule screen:
    input:
        "finished_QC",
        "QC/screen/sketch_comparison.tsv.gz",
    output:
        temp(touch("finished_screen")),


## overwrite commands in rules/download.snakefile
onsuccess:
    print("ATLAS finished")
    print("The last rule shows you the main output files")
onerror:
    print("Note the path to the log file for debugging.")
    print("Documentation is available at: https://metagenome-atlas.readthedocs.io")
    print("Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues")


## pepulate resources for rules that don't have
for r in workflow.rules:
    if not "mem_mb" in r.resources:
        if "mem" in r.resources:
            r.resources["mem_mb"] = r.resources["mem"] * 1000
        else:
            # default
            r.resources["mem_mb"] = config["mem"] * 1000

    # add time if ot present. Simple jobs use simple time
    if "time_min" not in r.resources:
        if "runtime" in r.resources:
            r.resources["time_min"] = r.resources["runtime"] * 60
        else:
            r.resources["time_min"] = config["runtime"] * 60
    
    if not "runtime" in r.resources:
        r.resources["runtime"] = config["runtime"]
