import os
import re
import sys
import tempfile
import pandas as pd
import numpy as np
from pathlib import Path
from snakemake.utils import min_version

# Minimum required snakemake version
min_version("9.17")

# Get package paths
working_dir = os.getcwd()
workflow_folder = workflow.basedir
scripts_dir = os.path.join(workflow_folder, "scripts")
package_dir = os.path.abspath(os.path.join(workflow_folder, "../"))
for p in [package_dir, scripts_dir]:
    if p not in sys.path:
        sys.path.append(p)
import utils # From 'workflow/scripts'

# Import and execute the logger setup module
from logger_setup import configure_snakemake_logger
configure_snakemake_logger(config)

# Set 'TMPDIR' for all rules. Set in multiple ways to ensure it hits shell, run, and script, even when containerized.
tmpdir = config.get("tmpdir", "/tmp")
os.environ["TMPDIR"] = tmpdir
envvars:
    "TMPDIR"
#shell.prefix(f"export TMPDIR='{tmpdir}'; set -euo pipefail; ")

# Add default config. Comand line adds user config
configfile: os.path.join(package_dir, "config", "default_config.yaml")

container: "docker://mambaorg/micromamba:2.5.0-cuda11.8.0-ubuntu22.04"
containerized: "docker://timothystephens/naive_atlas-envs:latest"

wildcard_constraints:
    binner="[A-Za-z]+",

include: "rules/sample_table.smk"
include: "rules/resources.smk" # contains hard coded variables
include: "rules/download.smk"  # contains hard coded variables
include: "rules/qc.smk"
include: "rules/assemble.smk"
include: "rules/binning.smk"
include: "rules/genomes.smk"
include: "rules/quantify_genomes.smk"
include: "rules/genome_annotation.smk"
include: "rules/gene_prediction.smk"
include: "rules/quantify_genes.smk"
include: "rules/gene_annotation.smk"
include: "rules/strains.smk"
include: "rules/screen.smk"  # expects function get_input_fastq defined in qc


localrules:
    all,
    download,
    qc,
    assembly_one_sample,
    assembly,
    binning,
    genomes,
    quantify_genomes,
    genome_annotation,
    gene_prediction,
    gene_annotation,
    strains,
    screen,
    test,



rule all:
    input:
        "finished_download",
        "finished_QC",
        "finished_assembly",
        "finished_binning",
        "finished_genomes",
        "finished_quantify_genomes",
        "finished_quantify_genes",
        "finished_genome_annotation",
        "finished_gene_annotation",


## ---- ##
rule test:
    input:
        rules.busco_download_db.output.dbdir,
    output:
        touch("finished_test"),


## ---- ##
DBDIR = os.path.realpath(config["database_dir"])
rule download:
    input:
        *get_databases_to_download(),
    output:
        touch("finished_download"),


## ---- ##
rule qc:
    input:
        expand("samples/{sample}/sequence_quality_control/finished_QC", sample=SAMPLES),
        read_counts="stats/read_counts.tsv",
        read_length_stats=["stats/insert_stats.tsv", "stats/read_length_stats.tsv"],
        report="reports/qc_report.html",
    output:
        touch("finished_QC"),


## ---- ##
rule assembly_one_sample:
    input:
        get_assembly,
        "samples/{sample}/assembly/contig_stats/postfilter_coverage_stats.txt",
        "samples/{sample}/assembly/contig_stats/final_contig_stats.txt",
    output:
        touch("samples/{sample}/finished_assembly"),

rule assembly:
    input:
        "finished_QC",
        expand("samples/{sample}/finished_assembly", sample=SAMPLES),
        "reports/assembly_report.html",
    output:
        touch("finished_assembly"),


## ---- ##
rule binning:
    input:
        "finished_assembly",
        expand(rules.binning_prokaryotic_genome_stats.output.stats, sample=SAMPLES),
        expand(rules.binning_eukaryotic_genome_stats.output.stats, sample=SAMPLES),
        expand(rules.binning_viral_genome_stats.output.viral_stats, sample=SAMPLES),
        expand(rules.binning_viral_genome_stats.output.plasmid_stats, sample=SAMPLES),
    output:
        temp(touch("finished_binning")),


## ---- ##
def get_bin_reports(wildcards):
    return(expand("reports/bin_report_{lineage}.html", 
                lineage=get_binned_lineages(wildcards)
            )
    )

rule genomes:
    input:
        "finished_binning",
        "genomes/genomes",
        "genomes/unbinned",
        get_bin_reports,
        rules.combine_name_mappings.output.c2g_all,
    output:
        temp(touch("finished_genomes")),


## ---- ##
rule quantify_genomes:
    input:
        "finished_genomes",
        "reports/quantify_genomes_mapping_results.html",
        get_coverm_files,
    output:
        temp(touch("finished_quantify_genomes")),


## ---- ##
def get_genome_annotations():
    annotation_file_names = {
        "gtdb_tree":                      "genomes/annotations/genomes/tree/finished_gtdb_trees",
        "gtdb_taxonomy":                  "genomes/annotations/genomes/taxonomy/gtdb_taxonomy.tsv",
        "metaeuk":                        expand("genomes/annotations/{dataset}/metaeuk_mag_predictions.tsv.gz", dataset="genomes"),
        "metaeuk_unbinned":               expand("genomes/annotations/{dataset}/metaeuk_mag_predictions.tsv.gz", dataset="unbinned"),
        "mmseqs2_easy_taxonomy":          expand("genomes/annotations/{dataset}/mmseqs2_easy_taxonomy_{database_name}_result_tophit_aln.tsv.gz", dataset="genomes",  database_name=config["mmseqs2_database_name"]),
        "mmseqs2_easy_taxonomy_unbinned": expand("genomes/annotations/{dataset}/mmseqs2_easy_taxonomy_{database_name}_result_tophit_aln.tsv.gz", dataset="unbinned", database_name=config["mmseqs2_database_name"]),
    }
    annotations_requested = config.get("genome_annotations") or []

    try:
        annotations_files = [
            annotation_file_names[an] for an in annotations_requested
        ]
    except Exception as e:
        raise IOError(
            "Error in annotations requested, check config file 'genome_annotations' "
        ) from e

    return annotations_files

rule genome_annotation:
    input:
        "finished_genomes",
        *get_genome_annotations(),
    output:
        temp(touch("finished_genome_annotation")),


## ---- ##
rule gene_prediction:
    input:
        "finished_genome_annotation",
        "genomes/annotations/genomes/taxonomy/gtdb_taxonomy.tsv",
        "genomes/genes/genomes",
        "genomes/genes/unbinned",
    output:
        temp(touch("finished_gene_prediction")),


## ---- ##
rule quantify_genes:
    input:
        "finished_gene_prediction",
        "genomes/genes/coverage/all_cds.coverage.tsv.gz",
    output:
        temp(touch("finished_quantify_genes")),


## ---- ##
def get_gene_annotations():
    annotation_file_names = {
        "eggNOG":                       expand("genomes/annotations/{dataset}/genes/emapper.tsv.gz", dataset="genomes"),
        "eggNOG_unbinned":              expand("genomes/annotations/{dataset}/genes/emapper.tsv.gz", dataset="unbinned"),
        "mmseqs2_easy_search":          expand("genomes/annotations/{dataset}/genes/mmseqs2_easy_search_{database_name}.m4.gz", dataset="genomes",  database_name=config["mmseqs2_database_name"]),
        "mmseqs2_easy_search_unbinned": expand("genomes/annotations/{dataset}/genes/mmseqs2_easy_search_{database_name}.m4.gz", dataset="unbinned", database_name=config["mmseqs2_database_name"]),
    }
    annotations_requested = config.get("gene_annotations") or []

    try:
        annotations_files = [
            annotation_file_names[key] for key in annotations_requested
        ]
    except Exception as e:
        raise IOError(
            "Error in gene_annotations requested, check config file 'gene_annotations' "
        ) from e

    return annotations_files

rule gene_annotation:
    input:
        "finished_genomes",
        get_gene_annotations(),
    output:
        temp(touch("finished_gene_annotation")),


## ---- ##
rule strains:
    input:
        "finished_genomes",
        "genomes/strains/comparison",
    output:
        temp(touch("finished_strains")),


## ---- ##
rule screen:
    input:
        "finished_QC",
        "genomes/screen/sketch_comparison.tsv.gz",
    output:
        temp(touch("finished_screen")),


## overwrite commands in rules/download.snakefile
onsuccess:
    print("naiveATLAS finished")
    print("The last rule shows you the main output files")
onerror:
    print("Note the path to the log file for debugging.")
    print("Issues can be raised at: https://github.com/TimothyStephens/naive_atlas/issues")
