#!/usr/bin/env bash
####
#### Script to automatically containerize and build naiveATLAS into docker
####
set -euo pipefail

## Print all info to log file
exec 1> >(tee -a "${0}.log") 2>&1


## Env vars
USER="timothystephens"
DOCKER=$(which docker)
DOCKERFILE="dockerfile"
DOCKERFILE_ENV="dockerfile_env"
VERSION=$(git describe --tags --dirty --always)
BUILD_ONLY=0
DEBUG=""


## Useage information
usage() {
echo -e "##
## $(basename ${0}) v${VERSION}
##

Script to automatically containerize and build naiveATLAS into docker

Usage:
$(basename $0) --debug

Options (all optional):
-b, --build_only           Only write 'dockerfile', dont build it.
-v, --version              Script version (${VERSION})
-h, --help                 This help message
--debug                    Run debug mode
" 1>&2
exit 1
}

# See https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -b|--build_only)
      BUILD_ONLY=1
      shift # past argument
      ;;
    -h|--help)
      usage
      exit 1;
      ;;
    -v|--version)
      echo "${VERSION}"
      exit 0;
      ;;
    --debug)
      set -x
      DEBUG="-v"
      shift # past argument
      ;;
    *) # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters


## Build dockerfile
echo "## Writing $DOCKERFILE_ENV.tmp"
echo -e "# Dockerfile to containerize naiveATLAS conda envs
FROM condaforge/mambaforge:latest


## (1/3) Set environment variables
# So we dont have to interactivly configure tzdata
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive

ENV CONDA_DIR=/conda-envs
ENV PATH=/conda-envs/naive_atlas/bin:\$PATH
# Enhance mamba network robustness
ENV MAMBA_NO_LOW_SPEED_LIMIT=1
ENV CONDA_REMOTE_READ_TIMEOUT_SECS=300

RUN apt-get update && \\
    apt-get install -y \\
      zlib1g zlib1g-dev build-essential gcc && \\
    rm -rf /var/lib/apt/lists/*


## (2/3) Install Singulairty
RUN apt-get update && \\
    apt-get install -y --no-install-recommends \\
      software-properties-common \\
      gnupg \\
      ca-certificates \\
    && add-apt-repository -y ppa:apptainer/ppa \\
    && apt-get update \\
    && apt-get install -y apptainer \\
    && rm -rf /var/lib/apt/lists/*


## (3/3) Install each workflow package" > "$DOCKERFILE_ENV.tmp"

RUN=""
tmp_seen=$(mktemp)
for YAML in workflow/envs/*.yaml;
do

MD5SUM=$(md5sum "$YAML" | awk '{print $1}')

# Check if we have seen this md5sum previously
if ! grep -qFx "$MD5SUM" "$tmp_seen"; then
  # Not seen
  echo "# Conda environment:" >> "$DOCKERFILE_ENV.tmp"
  echo "#   source: $YAML" >> "$DOCKERFILE_ENV.tmp"
  echo "#   prefix: /conda-envs/$MD5SUM" >> "$DOCKERFILE_ENV.tmp"
  awk '{print "#   "$0}' "$YAML"   >> "$DOCKERFILE_ENV.tmp"
  echo -e "COPY $YAML /conda-envs/$MD5SUM.yaml" >> "$DOCKERFILE_ENV.tmp"
  echo -e "RUN mamba env create ${DEBUG} \\" >> "$DOCKERFILE_ENV.tmp"
  echo -e "      --prefix /conda-envs/$MD5SUM \\" >> "$DOCKERFILE_ENV.tmp"
  echo -e "      --file   /conda-envs/$MD5SUM.yaml -vvv && \\" >> "$DOCKERFILE_ENV.tmp"
  echo -e "    mamba clean -afy" >> "$DOCKERFILE_ENV.tmp"
  echo "" >> "$DOCKERFILE_ENV.tmp"
  
  echo "$MD5SUM" >> "$tmp_seen"
  
else
  # Seen
  echo "# Conda environment:" >> "$DOCKERFILE_ENV.tmp"
  echo "#   source: $YAML" >> "$DOCKERFILE_ENV.tmp"
  echo "#   prefix: /conda-envs/$MD5SUM" >> "$DOCKERFILE_ENV.tmp"
  awk '{print "#   "$0}' "$YAML"   >> "$DOCKERFILE_ENV.tmp"
  echo -e "# NOTRUN: Seen md5sum previously" >> "$DOCKERFILE_ENV.tmp"
  echo "" >> "$DOCKERFILE_ENV.tmp"

fi

done
rm "$tmp_seen"

# Hard coded wrappers since generating the md5sums is based on how it is listed online and not locally.
# To prevent needing to download this info we just hard code the builds.
echo "# Conda environment:
#   source: https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v1.19.0/bio/samtools/stats/environment.yaml
#   prefix: /conda-envs/7c07ea7ec21294e0ded29ba6e2d362e2
#   channels:
#     - conda-forge
#     - bioconda
#     - nodefaults
#   dependencies:
#     - samtools=1.14
#     - snakemake-wrapper-utils=0.3
ADD https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v1.19.0/bio/samtools/stats/environment.yaml /conda-envs/7c07ea7ec21294e0ded29ba6e2d362e2.yaml
RUN mamba env create  \
      --prefix /conda-envs/7c07ea7ec21294e0ded29ba6e2d362e2 \
      --file   /conda-envs/7c07ea7ec21294e0ded29ba6e2d362e2.yaml -vvv && \
    mamba clean -afy

# Conda environment:
#   source: https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v3.13.4/bio/minimap2/index/environment.yaml
#   prefix: /conda-envs/a2d30c5606f0ad1617dd954cca5b465b
#   channels:
#     - conda-forge
#     - bioconda
#     - nodefaults
#   dependencies:
#     - minimap2 =2.28
ADD https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v3.13.4/bio/minimap2/index/environment.yaml /conda-envs/a2d30c5606f0ad1617dd954cca5b465b.yaml
RUN mamba env create  \
      --prefix /conda-envs/a2d30c5606f0ad1617dd954cca5b465b \
      --file   /conda-envs/a2d30c5606f0ad1617dd954cca5b465b.yaml -vvv && \
    mamba clean -afy

# Conda environment:
#   source: https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v3.3.6/bio/multiqc/environment.yaml
#   prefix: /conda-envs/ecf1e3c321150b029c4ee6071ab30a6e
#   channels:
#     - conda-forge
#     - bioconda
#     - nodefaults
#   dependencies:
#     - multiqc =1.19
ADD https://raw.githubusercontent.com/snakemake/snakemake-wrappers/v3.3.6/bio/multiqc/environment.yaml /conda-envs/ecf1e3c321150b029c4ee6071ab30a6e.yaml
RUN mamba env create  \
      --prefix /conda-envs/ecf1e3c321150b029c4ee6071ab30a6e \
      --file   /conda-envs/ecf1e3c321150b029c4ee6071ab30a6e.yaml -vvv && \
    mamba clean -afy
" >> "$DOCKERFILE_ENV.tmp"

echo "## Done writing $DOCKERFILE_ENV.tmp"

if ! cmp -s "$DOCKERFILE_ENV.tmp" "$DOCKERFILE_ENV"; then
  echo "## $DOCKERFILE_ENV.tmp is different from $DOCKERFILE_ENV, we will NEED to rebuild!"
  mv "$DOCKERFILE_ENV.tmp" "$DOCKERFILE_ENV"
  if [ $BUILD_ONLY -eq 1 ];
  then
    echo "## Skipping docker build!"
  else
    echo "## Building $DOCKERFILE_ENV"
    $DOCKER build -t $USER/naive_atlas-envs:${VERSION} -t $USER/naive_atlas-envs:latest -f $DOCKERFILE_ENV .
    echo "## Done building $DOCKERFILE_ENV"
  fi
else
  echo "## $DOCKERFILE_ENV.tmp is the same as $DOCKERFILE_ENV, NO NEED to rebuild!"
  rm "$DOCKERFILE_ENV.tmp"
fi

echo ""



## Build dockerfile
echo "## Writing $DOCKERFILE"
echo -e "# Dockerfile to containerize naiveATLAS workflow
FROM condaforge/mambaforge:latest


## (1/6) Set environment variables
# So we dont have to interactivly configure tzdata
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive

ENV CONDA_DIR=/conda-envs
ENV PATH=/conda-envs/naive_atlas/bin:\$PATH
# Enhance mamba network robustness
ENV MAMBA_NO_LOW_SPEED_LIMIT=1
ENV CONDA_REMOTE_READ_TIMEOUT_SECS=300

RUN apt-get update && \\
    apt-get install -y \\
      zlib1g zlib1g-dev build-essential gcc && \\
    rm -rf /var/lib/apt/lists/*


## (2/6) Install Singulairty
RUN apt-get update && \\
    apt-get install -y --no-install-recommends \\
      software-properties-common \\
      gnupg \\
      ca-certificates \\
    && add-apt-repository -y ppa:apptainer/ppa \\
    && apt-get update \\
    && apt-get install -y apptainer \\
    && rm -rf /var/lib/apt/lists/*


## (3/6) Create and set workflow working directory
WORKDIR /app
COPY . .
RUN sed -e 's@timothystephens/naive_atlas-envs:latest@timothystephens/naive_atlas-envs:${VERSION}@' -i workflow/Snakefile
RUN mamba env create --prefix /conda-envs/naive_atlas --file naive_atlasenv_cluster.yml -v
SHELL [\"conda\", \"run\", \"-p\", \"/conda-envs/naive_atlas\", \"/bin/bash\", \"-c\"]
RUN /conda-envs/naive_atlas/bin/pip install --prefix /conda-envs/naive_atlas --editable .


## (4/6) Verify the installation by checking the version
RUN naive_atlas --help


## (5/6) Set the default command to test naive_atlas
CMD [\"naive_atlas\", \"--help\"]

## (6/6) Download containers" > "$DOCKERFILE"

# Docker container
echo "RUN mkdir -p /singulairty" >> "$DOCKERFILE"
grep -A2 'container' workflow/Snakefile workflow/rules/*.smk \
  | grep '://' \
  | awk '{print $2}' \
  | sed -e s'/",//' -e 's/"//g' \
  | sort | uniq \
  | grep -v 'naive_atlas-envs' \
  | while read DOCKER;
    do
      MD5=$(echo -n "$DOCKER" | md5sum | awk '{print $1}')
      echo "RUN apptainer pull --dir /singulairty ${MD5}.sif \"${DOCKER}\" && apptainer cache clean --force"
    done >> "$DOCKERFILE"
#echo "RUN apptainer pull --dir /singulairty b0cbfcaa12aed20fbe0a5297d12b5d21.sif \"docker-daemon://timothystephens/naive_atlas-envs:latest\" && apptainer cache clean --force" >> "$DOCKERFILE"
echo "RUN apptainer pull --dir /singulairty b0cbfcaa12aed20fbe0a5297d12b5d21.sif \"docker-archive:///app/naive_atlas-envs.tar\" && apptainer cache clean --force" >> "$DOCKERFILE"
echo "RUN rm -f /app/naive_atlas-envs.tar" >> "$DOCKERFILE"

echo "## Done writing $DOCKERFILE"
if [ $BUILD_ONLY -eq 1 ];
then
  echo "## Skipping docker build!"
else
  echo "## Building $DOCKERFILE"
  $DOCKER build -t $USER/naive_atlas:${VERSION} -t $USER/naive_atlas:latest -f $DOCKERFILE .
  $DOCKER run $USER/naive_atlas:${VERSION} naive_atlas --help
  rm -f naive_atlas-envs.tar
  echo "## Done building $DOCKERFILE"
fi



## Print commands to check the build
echo -e "

# Run these commands once you are happy with the containerize version
docker push $USER/naive_atlas-envs:${VERSION} && docker push $USER/naive_atlas-envs:latest
docker push $USER/naive_atlas:${VERSION}      && docker push $USER/naive_atlas:latest
docker image ls
docker image rm XXXX


# Once it is uploaded, test using singularity
singularity pull naive_atlas_${VERSION}.sif docker://$USER/naive_atlas:${VERSION}
singularity exec naive_atlas_${VERSION}.sif naive_atlas --help
rm naive_atlas_${VERSION}.sif

# OR build a SIF file directly from a local docker image
singularity build naive_atlas_${VERSION}.sif docker-daemon://$USER/naive_atlas:${VERSION}
singularity exec naive_atlas_${VERSION}.sif naive_atlas --help
rm naive_atlas_${VERSION}.sif
"


