#==========================================================================================
#
#                    ..
#      _ __    __ _  _   _   _   ___     █████╗ ████████╗██╗      █████╗ ███████╗
#     | '_ \  / _` || | | | | | / _ \   ██╔══██╗╚══██╔══╝██║     ██╔══██╗██╔════╝
#     | | | | |(_| || | | |_| | | __/   ███████║   ██║   ██║     ███████║███████╗
#     |_| |_| \__,_||_|  \___/  \___|   ██╔══██║   ██║   ██║     ██╔══██║╚════██║
#                                       ██║  ██║   ██║   ███████╗██║  ██║███████║
#                                       ╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚══════╝
#
#
#==========================================================================================





########################
# Execution parameters
########################
#Runtime only for cluster execution
#Threads and Memory for all executions

# Global safety cap for any single job (in MB)
max_mem_mb: 1500000 # 1,500 GB

# Partition mapping (for SLURM or other schedulers): partition_name -> threshold (mem_mb)
account: "general"
partition_ranges:
  main-redhat: 160000
  mem: 1500000

# Default resources for simple or low resource jobs (not requiring dynamic scaling)
simple_job_mem_mb: 5000
simple_job_threads: 8
simple_job_time_min: 1440 # 24 hr

# Resources for rules requiring dynamic scaling (i.e., QC or assembly jobs)
dynamic_threads: &dynamic_default_threads 24
dynamic_time_min: &dynamic_default_time_min 4320 # 72 hr

resources:
  ################
  #### qc.smk ####
  ################
  initialize_qc:
    base_mem_mb: 2000
    scaling_factor: 0.2
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  deduplicate_reads:
    base_mem_mb: 8000
    scaling_factor: 3.5
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  apply_quality_filter:
    base_mem_mb: 8000
    scaling_factor: 2.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  build_decontamination_db:
    base_mem_mb: 12000
    scaling_factor: 1.5
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  run_decontamination:
    base_mem_mb: 12000
    scaling_factor: 1.5
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  get_read_counts:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  get_read_length_hist:
    base_mem_mb: 8000
    scaling_factor: 12.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  
  ######################
  #### assembly.smk ####
  ######################
  normalize_reads:
    base_mem_mb: 8000
    scaling_factor: 6.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  error_correction:
    base_mem_mb: 8000
    scaling_factor: 6.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  run_assembly:
    base_mem_mb: 12000
    scaling_factor: 6.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  mapping:
    base_mem_mb: 8000
    scaling_factor: 1.5
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  pileup:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  filter_by_coverage:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  rename_contigs:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  calculate_contigs_stats:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  samtools_stats_contigs_sample:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  create_bam_index:
    base_mem_mb: 2000
    scaling_factor: 0.1
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  
  #####################
  #### binning.smk ####
  #####################
  binning:
    base_mem_mb: 40000
    scaling_factor: 2.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
 
  #####################
  #### genomes.smk ####
  #####################
  run_skani:
    base_mem_mb: 20000
    scaling_factor: 1.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  skani_2_parquet:
    base_mem_mb: 20000
    scaling_factor: 1.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  cluster_species:
    base_mem_mb: 20000
    scaling_factor: 1.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  run_cdhit:
    base_mem_mb: 20000
    scaling_factor: 1.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
   
  ######################
  #### download.smk ####
  ######################
  download:
    base_mem_mb: 60000
    scaling_factor: 0.0
    threads: 2
    time_min: *dynamic_default_time_min
  
  #############################
  #### gene_prediction.smk ####
  #############################
  predict_genes:
    base_mem_mb: 80000
    scaling_factor: 2
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  
  #############################
  #### gene_annotation.smk ####
  #############################
  gene_annot_eggnog:
    base_mem_mb: 30000
    scaling_factor: 0.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  gene_annot_mmseqs2_easy_search:
    base_mem_mb: 80000
    scaling_factor: 0.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  
  ###############################
  #### genome_annotation.smk ####
  ###############################
  genome_annot_gtdbtk:
    base_mem_mb: 120000
    scaling_factor: 0.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  genome_annot_gtdbtk_tree:
    base_mem_mb: 10000
    scaling_factor: 0.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  genome_annot_metaeuk:
    base_mem_mb: 160000
    scaling_factor: 0.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  genome_annot_mmseqs2_easy_taxonomy:
    base_mem_mb: 160000
    scaling_factor: 0.0
    threads: *dynamic_default_threads
    time_min: *dynamic_default_time_min
  
  ###########################################################################################
  #### All local rules ('touch' or combine rules - run on main node if using SLURM/etc.) ####
  ###########################################################################################
  localrule:
    base_mem_mb: 5000
    scaling_factor: 0.0
    threads: 1
    time_min: 1440 # 24 hrs





########################
# Paths to reference genomes and databases
########################
# directory where databases are downloaded with 'atlas download'
database_dir: 
  /user/project/dir/databases

tmpdir: 
  /tmp





########################
# Quality control
########################
importqc_params: "iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t"

# remove (PCR)-duplicated reads using clumpify
deduplicate: true
duplicates_only_optical: false
duplicates_allow_substitutions: 2

# used to trim adapters from reads and read ends
#preprocess_adapters: /user/adapters.fa
preprocess_qtrim: "rl"
preprocess_kmer_trim: "r"
preprocess_minimum_base_quality: 10
preprocess_allowable_kmer_mismatches: 1
preprocess_reference_kmer_match_length: 27
preprocess_minimum_passing_read_length: 51

preprocess_max_ns: -1
preallocate_ram: "t"

# 0.05 requires at least 5 percent of each nucleotide per sequence
preprocess_minimum_base_frequency: 0.05
preprocess_adapter_min_k: 8
preprocess_allowable_kmer_mismatches: 1
preprocess_reference_kmer_match_length: 27
# normalize reads
normalize_reads_before_assembly: false
normalization_kmer_length: 21
normalization_target_depth: 1000
normalization_minimum_kmer_depth: 3
# error correction where PE reads overlap
error_correction_overlapping_pairs: true
#contamination references can be added such that -- key: /path/to/fasta
contaminant_references:
contaminant_references_include_phiX: true
contaminant_max_indel: 20
contaminant_min_ratio: 0.65
contaminant_kmer_length: 13
contaminant_minimum_hits: 1
contaminant_ambiguous: best 
# Read length hist
bbmerge_minprob: 0.8
merging_extend2: 50





########################
# Assembly
########################

# remove reads with k-mers that cannot be used for assembly.
# Filter reads that have a 10% of k-mers below a minimum depth.
error_correction_remove_lowdepth: false
error_correction_minimum_kmer_depth: 1
error_correction_lowdepth_fraction: 0.5
error_correction_aggressive: false
error_correction_minprob: 0.5
error_correction_kmer: 31 # can be longer e.g. 62 but takes more memory

# Merging of pairs
# join R1 and R2 at overlap; unjoined reads are still utilized
merge_pairs_before_assembly: true
merging_k: 62

# Megahit
#-----------
# 2 is for metagenomes, 3 for genomes with 30x coverage
megahit_min_count: 2
megahit_k_min: 21
megahit_k_max: 121
megahit_k_step: 20
megahit_merge_level: 20,0.98
megahit_prune_level: 2
megahit_low_local_ratio: 0.2
# ['default','meta-large','meta-sensitive']
megahit_preset: default
megahit_extra: ''

# Spades
#------------
spades_use_scaffolds: true # if false use contigs
spades_skip_BayesHammer: true # Skip error correction in spades assembler
#Comma-separated list of k-mer sizes to be used (all values must be odd, less than 128 and listed in ascending order).
spades_k: auto
spades_extra: ''

# Flye
#------------
flye_extra: ''

# metaMDBG
#------------
metamdbg_extra: ''

# Filtering
#------------
count_multi_mapped_reads: false
# filter out assembled noise
minimum_contig_length: 1000
# trim contig tips
contig_trim_bp: 0
# require contigs to have read support
minimum_average_coverage: 1
minimum_percent_covered_bases: 20
minimum_mapped_reads: 0
minimum_map_quality: 0





########################
# Binning
########################

cobinning_readmapping_id: 0.95

veba_prokaryotic:
  minimum_contig_length: 1500 # Minimum contig length. Anything under 2500 will default to 2500 for MetaBat2.
  minimum_genome_length: 150000 # Minimum prokaryote genome length.
  checkm2_completeness: 50 # CheckM2 completeness threshold.
  checkm2_contamination: 10 # CheckM2 contamination threshold.
  mdmcleaner_skip: false # Skip MDMcleaner step (very long runtime on rich prokaryotic microbiomes)
  mdmcleaner_options: '' # MDMcleaner commandline options. e.g., '--fast_run'

veba_eukaryotic:
  minimum_contig_length: 1500 # Minimum contig length. Anything under 2500 will default to 2500 for MetaBat2.
  minimum_genome_length: 2000000 # Minimum eukaryote genome length.
  busco_completeness: 10 # BUSCO completeness threshold.
  busco_contamination: 10 # BUSCO contamination threshold.

veba_viral:
  minimum_contig_length: 1500 # Minimum contig length. Anything under 2500 will default to 2500 for MetaBat2.
  minimum_genome_length: 2500 # Minimum viral/plastid genome length.
  minimum_score: 0.7 # Minimum score to flag a sequence as virus or plasmid.

genome_dereplication:
  ANI: 0.95 # Genome dreplication threshold 0.95 is more or less species
  overlap: 0.2 # See more on https://drep.readthedocs.io/en/latest/module_descriptions.html

unbinned_dereplication:
  cdhitest_params: "-c 0.95 -n 9 -aS 0.9 -d 0 -M 0"

rename_mags_contigs: true #Rename contigs of representative MAGs (should be kept on - turning off may cause unexpected errors in renaming of MAGs after clustering)





########################
# Quantification
########################

coverm_params: '--min-read-percent-identity 95 --min-covered-fraction 0 --min-read-aligned-percent 70'
coverm_stats: 'relative_abundance mean trimmed_mean covered_bases variance length count reads_per_base rpkm tpm'





########################
# Genome Annotations
#######################

genome_annotations: []

mmseqs2_database: "UniRef100" # UniRef100, UniRef90, UniRef50, UniProtKB, UniProtKB/TrEMBL, UniProtKB/Swiss-Prot, NR, GTDB
mmseqs2_database_name: "UniRef100"
mmseqs2_memory: 120 #GB of memory for mmseqs2 annotation of genes and genomes - Needs to be bigger if using larger databases (UniRef100, NR, UniProtKB/TrEMBL, GTDB)

## mmseqs2 easy-taxonomy
# Gene annotation
mmseqs2_opts: ""
mmseqs2_format_output: "query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,qlen,tlen,taxid,taxname,taxlineage,theader"
# Genome easy-taxonomy
mmseqs2_easy_taxonomy: ""

## MetaEuk
metaeuk_createdb: ""
metaeuk_predictexons: "--metaeuk-eval 0.0001 -e 100 --min-length 40"
metaeuk_reduceredundancy: ""
metaeuk_unitesetstofasta: ""
metaeuk_taxtocontig: "--majority 0.5 --tax-lineage 1 --lca-mode 2"





########################
# Gene annotations
#######################

gene_annotations: []

eggNOG_use_virtual_disk: false # coping the eggNOG DB to a virtual disk can speed up the annotation
virtual_disk: /dev/shm   # But you need 37G extra ram





########################
# Misc
#######################
instrain_profile_extra: ""
instrain_compare_extra: ""

## use just in time compilation for bbmap
usejni: false
