## use just in time compilation for bbmap
usejni: false


########################
# Quality control
########################

preprocess_qtrim: "rl"
preprocess_kmer_trim: "r"
preprocess_minimum_base_quality: 10
preprocess_allowable_kmer_mismatches: 1
preprocess_reference_kmer_match_length: 27
preprocess_minimum_passing_read_length: 51
preprocess_minimum_base_frequency: 0.05
preprocess_max_ns: -1
preallocate_ram: "t"
error_correction_overlapping_pairs: "t"


########################
# Quantification
########################

genome_aligner: "minimap"


########################
# Binning
########################

cobinning_readmapping_id: 0.95

genome_dereplication:
  ANI: 0.95 ## Genome dreplication threshold
  overlap: 0.2 # See more on https://drep.readthedocs.io/en/latest/module_descriptions.html
  greedy_clustering: "auto" # Add options for greedy clustering 'auto' when using more than 5k bins
  opt_parameters: ""
  score:
    completeness: 1
    contamination: 5
    N50: 0.5
    length: 0
    centrality: 1


########################
# Gene catalog
#######################

gene_annotations: []


