#####################################################################
####                   _______   _                    _____      ####
####           /\     |__   __| | |          /\      / ____|     ####
####          /  \       | |    | |         /  \    | (___       ####
####         / /\ \      | |    | |        / /\ \    \___ \      ####
####        / ____ \     | |    | |____   / ____ \   ____) |     ####
#### Naive /_/    \_\    |_|    |______| /_/    \_\ |_____/      ####
####                                                             ####
#####################################################################

#  For more details about the config values see:
#  https://metagenome-atlas.rtfd.io



########################
# Execution parameters
########################
#Runtime only for cluster execution

# BBMAPs tools threads and memory - needs relatively high amount of memory: normalize_reads, error_correction, merge_pairs
large_memory: 150 #GB
large_threads: 46
large_runtime: 24 #hr
# Assembly threads and memory: run_megahit, run_spades
assembly_memory: 350 #GB
assembly_threads: 60
assembly_runtime: 48 #hr
# All other major analysis rules Simple text parsing jobs
simplejob_memory: 20 #GB
simplejob_threads: 8
simplejob_runtime: 24 #hr
# Simple text parsing jobs
mem: 2 #GB
threads: 8
runtime: 4 #hr



########################
# Paths to reference genomes and databases
########################
# directory where databases are downloaded with 'atlas download'
database_dir: 
  /user/project/dir/databases

tmpdir: 
  /user/project/dir/tmp

# used to trim adapters from reads and read ends
preprocess_adapters: 
  /user/project/dir/databases/adapters.fa

#contamination references can be added such that -- key: /path/to/fasta
contaminant_references:
  PhiX: 
    /user/project/dir/databases/phiX174_virus.fa
  Host_A:
    /user/project/host_refs/Host_A.fa
  Host_B:
    /user/project/host_refs/Host_B.fa



########################
# Annotations
########################
genome_annotations:
- gtdb_tree
- gtdb_taxonomy
- dram
- metaeuk
- metaeuk_unbinned

gene_annotations:
- eggNOG
- dram


