#==========================================================================================
#
#                    ..
#      _ __    __ _  _   _   _   ___     █████╗ ████████╗██╗      █████╗ ███████╗
#     | '_ \  / _` || | | | | | / _ \   ██╔══██╗╚══██╔══╝██║     ██╔══██╗██╔════╝
#     | | | | |(_| || | | |_| | | __/   ███████║   ██║   ██║     ███████║███████╗
#     |_| |_| \__,_||_|  \___/  \___|   ██╔══██║   ██║   ██║     ██╔══██║╚════██║
#                                       ██║  ██║   ██║   ███████╗██║  ██║███████║
#                                       ╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚══════╝
#
#
#==========================================================================================



########################
# Paths to reference genomes and databases
########################
# directory where databases are downloaded with 'atlas download'
database_dir: 
  /user/project/dir/databases

tmpdir: 
  /user/project/dir/tmp

#contamination references can be added such that -- key: /path/to/fasta
contaminant_references:
  Host_A:
    /user/project/host_refs/Host_A.fa
  Host_B:
    /user/project/host_refs/Host_B.fa


########################
# Binning
########################
veba_prokaryotic:
  mdmcleaner_skip: false # Skip MDMcleaner step (very long runtime on rich prokaryotic microbiomes)
  mdmcleaner_options: '' # MDMcleaner commandline options. e.g., '--fast_run' to reduce runtime


########################
# Annotations
########################
genome_annotations:
- gtdb_tree
- gtdb_taxonomy
#- metaeuk
#- metaeuk_unbinned
#- mmseqs2_easy_taxonomy
#- mmseqs2_easy_taxonomy_unbinned

gene_annotations:
- eggNOG
- eggNOG_unbinned
#- mmseqs2_easy_search
#- mmseqs2_easy_search_unbinned



