name: Combined Workflow

on: [push]

defaults:
  run:
    shell: bash -el {0} # use default shell
jobs:
  build-and-dryrun:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2


    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Get current month
        id: date
        run: echo "date=$(date +%Y-%m)" >> "${GITHUB_OUTPUT}"

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: atlasenv.yml
          environment-name: atlasenv
          # persist on the same month.
          cache-environment-key: atlasenv-${{ steps.date.outputs.date }}


      - name: Install atlas
        run: |
           python -m pip install . --no-deps -vv

      - name: Test atlas
        run: |
          atlas --help
          atlas --version

      - name: test import modules atlas
        run: |
          python -c "from atlas import utils"

      - name: Dryrun
        run: test/dryrun.sh

      - name: Test init many samples
        run: ./test/test_init_many_samples.sh

      # - name: Cache atlas instalation
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-atlas
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
    
  full-test:
    runs-on: ubuntu-latest
    needs: build-and-dryrun
    strategy:
      max-parallel: 1
    env:
      N_THREADS: 2
      MEM: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: atlasenv.yml
          environment-name: atlasenv
          # persist on the same month.
          cache-environment-key: atlasenv-


      - name: Install atlas
        run: |
          python -m pip install . --no-deps -vv
          atlas --help

      - name: Clone Example Data Repository
        run: git clone https://github.com/metagenome-atlas/example_data.git
      
      - name: Run Test
        run: |
          ls -l 
          ls -l example_data
          chmod +x test/test_ci.sh
          test/test_ci.sh --resources mem=$MEM java_mem=$MEM --jobs=$N_THREADS --restart-times=2

      - name: Store Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: test_ci/logs

      - name: Store Sample Logs
        uses: actions/upload-artifact@v2
        with:
          name: sample_logs
          path: test_ci/Streptococcus/logs
