name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -el {0} # use default shell

    steps:

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Get current month
        id: date
        run: echo "date=$(date +%Y-%m)" >> "${GITHUB_OUTPUT}"

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: atlasenv.yml
          environment-name: atlasenv
          # persist on the same month.
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}

      - name: check mamba
        run: mamba --help

      - name: Install atlas
        run: |
           python -m pip install . --no-deps -vv
      - name: Test atlas
        run: |
          atlas --help
          atlas --version
      - name: Import atlas
        run: |
          python -c "from atlas import utils"

      - name: Dryrun
        run: |
          test/dryrun.sh
      - run:
        name: Test init many samples
        run: |
            ./test/test_init_many_samples.sh

